# This is a basic workflow

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
permissions:
  contents: read

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    permissions:
      checks: write  # for coverallsapp/github-action to create new checks
      contents: read  # for docker/build-push-action to read repo content
      security-events: write  # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      # Set up Node
      - name: Use Node 16
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"

      # Run install dependencies
      - name: Install dependencies
        run: yarn

      # Build extension
      - name: Run build
        run: yarn build

      - name: Generate SARIF
        if: matrix.os == 'ubuntu-latest'
        run: yarn lint-ci

      - name: Upload SARIF file
        if: matrix.os == 'ubuntu-latest'
        uses: github/codeql-action/upload-sarif@17573ee1cc1b9d061760f3a006fc4aac4f944fd5 #v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: eslint-result.sarif
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: eslint

      # Run tests
      - name: Run Test
        uses: GabrielBB/xvfb-action@fe2609f8182a9ed5aee7d53ff3ed04098a904df2 #v1.0
        with:
          run: yarn coveralls

        # Run Coveralls
      - name: Coveralls
        uses: coverallsapp/github-action@3284643be2c47fb6432518ecec17f1255e8a06a6 #master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        if: ${{ success() && runner.os == 'Linux' && github.event_name == 'push' && github.ref == 'refs/heads/main'}}
        run: yarn publish --tag next --no-git-tag-version --prepatch --preid "$(git rev-parse --short HEAD)"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

        # Setup QEMU as requirement for docker
      - name: Set up QEMU
        if: ${{ success() && runner.os == 'Linux' && github.event_name == 'push' && github.ref == 'refs/heads/main'}}
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480 # v1.2.0

        # Setup DockerBuildx as requirement for docker
      - name: Set up Docker Buildx
        if: ${{ success() && runner.os == 'Linux' && github.event_name == 'push' && github.ref == 'refs/heads/main'}}
        uses: docker/setup-buildx-action@f211e3e9ded2d9377c8cadc4489a4e38014bc4c9 # v1.7.0

        # Login to Quay
      - name: Login to Quay
        if: ${{ success() && runner.os == 'Linux' && github.event_name == 'push' && github.ref == 'refs/heads/main'}}
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # v1.14.1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

        # Build and push the latest version of yaml language server image
      - name: Build and push
        if: ${{ success() && runner.os == 'Linux' && github.event_name == 'push' && github.ref == 'refs/heads/main'}}
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a # v2.10.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: quay.io/redhat-developer/yaml-language-server:next
