# This is a basic workflow to help you get started with Actions

name: Release to NPM

# Controls when the action will run. Triggers the workflow on new tag
on:
  push:
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Harden Runner
      uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
      with:
        egress-policy: audit

    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      # Set up Node
    - name: Use Node 16 
      uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
      with:
        node-version: 16
        registry-url: 'https://registry.npmjs.org'

      # Run install dependencies
    - name: Install dependencies
      run: yarn

      # Build extension
    - name: Run build
      run: yarn build

      # Run tests
    - name: Run Test
      run: yarn test

      # Publish to npm
    - run: |
        yarn check-dependencies
        yarn publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      # Get the current package.json version so we can tag the image correctly
    - name: Get current package.json version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@7aa1d82604bb2dbe377a64ca35e692e6fe333c9c #master

      # Setup QEMU as requirement for docker
    - name: Set up QEMU
      uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480 # v1.2.0
      
      # Setup DockerBuildx as requirement for docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f211e3e9ded2d9377c8cadc4489a4e38014bc4c9 # v1.7.0

      # Login to Quay
    - name: Login to Quay
      uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # v1.14.1 
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}

      # Build and push the latest version of yaml language server image
    - name: Build and push
      uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a # v2.10.0
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          quay.io/redhat-developer/yaml-language-server:latest
          quay.io/redhat-developer/yaml-language-server:${{ steps.package-version.outputs.current-version}}
